name: Test and Build OCaml APM Client

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        ocaml-version:
          - 4.13.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - run: echo "⚡️ Ride the Camel"

      - run: opam install ./elastic-apm.opam --deps-only -y

      - run: eval $(opam env) && dune build @runtest && dune build

      - run: shasum -a 256 _build/default/META.elastic-apm
