name: Test and Build OCaml APM Client

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: echo "⚡️ Ride the Camel"